/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.ViewAux.BuscaCliente;
import br.com.control.Controlador;
import br.com.model.ClienteModel;
import br.com.utils.FormataData;
import br.com.utils.ValidaData;
import br.com.utils.Validacoes;
import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.joda.time.LocalDate;

/**
 *
 * @author diogenes.francisco
 */
public class TelaCliente extends javax.swing.JDialog {

    /**
     * Creates new form TelaCliente
     */
    ClienteModel cli = new ClienteModel();
    Frame pai;
    ;
    
    public TelaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        this.pai = parent;
    }

    public TelaCliente(java.awt.Frame parent, boolean modal, ClienteModel cliente) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        this.pai = parent;
        jTNome.setText(cliente.getNome());
        jTNomeFantasia.setText(cliente.getNomeFantasia());
        jTCodigo.setText(cliente.getId());
        jTCpf.setText(cliente.getCpf());
        jTCnpj.setText(cliente.getCnpj());
        jTRg.setText(cliente.getRg());
        if (cliente.getDataNasc() != null) {
            jTDtNasc.setText(FormataData.dateForApp(cliente.getDataNasc()));
        } else {
            jTDtNasc.setText("");
        }
        jTNaturalidade.setText(cliente.getNaturalidade());
        jTIE.setText(cliente.getIe());
        jTEndereco.setText(cliente.getEndereco());
        jTNumero.setText(cliente.getNumero());
        jTComplemento.setText(cliente.getComplemento());
        jTBairro.setText(cliente.getBairro());
        jTCidade.setText(cliente.getCidade());
        jTCep.setText(cliente.getCep());
        jComboEstado.setSelectedItem(cliente.getEstado());

        jTContato.setText(cliente.getContato());
        jTContato2.setText(cliente.getContato2());
        jTEmail.setText(cliente.getEmail());

        jTObs.setText(cliente.getObservacao());
        jTDataAlter.setText(FormataData.dateForApp(cliente.getDataAlteracao()));
        jTUsuarioCadastro.setText(cliente.getUsuario());
        if (cliente.getTipoCliente().equals("F")) {
            jRPesFisica.setSelected(true);
            jTCnpj.setEnabled(false);
            jTNomeFantasia.setEnabled(false);
            jTIE.setEnabled(false);
            jTCpf.setEnabled(true);
            jTDtNasc.setEnabled(true);
            jTNaturalidade.setEnabled(true);
            jTRg.setEnabled(true);
            jRFem.setEnabled(true);
            jRMasc.setEnabled(true);
        } else {
            jRPesJuridica.setSelected(true);
            jTCpf.setEnabled(false);
            jTDtNasc.setEnabled(false);
            jTNaturalidade.setEnabled(false);
            jTRg.setEnabled(false);
            jRFem.setEnabled(false);
            jRMasc.setEnabled(false);
            jTCnpj.setEnabled(true);
            jTNomeFantasia.setEnabled(true);
            jTIE.setEnabled(true);
        }

        if (!(cliente.getSexo() == null) && cliente.getSexo().equals("M")) {
            jRMasc.setSelected(true);
        } else if (!(cliente.getSexo() == null)) {
            jRFem.setSelected(true);
        }
        jCheckSituacao.setSelected(cliente.getAtivo());
    }

    public ClienteModel getCli() {
        return cli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnGroupTipoPessoa = new javax.swing.ButtonGroup();
        BtnGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTPesquisa = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRPesJuridica = new javax.swing.JRadioButton();
        jRPesFisica = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTCnpj = new javax.swing.JFormattedTextField();
        jTCpf = new javax.swing.JFormattedTextField();
        jTNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTRg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTDtNasc = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTNaturalidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTIE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTNomeFantasia = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRFem = new javax.swing.JRadioButton();
        jRMasc = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jTNumero = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTEndereco = new javax.swing.JTextField();
        jComboEstado = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTCep = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jTComplemento = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTContato = new javax.swing.JFormattedTextField();
        jTContato2 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTCodigo = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObs = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTDataAlter = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTUsuarioCadastro = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jCheckSituacao = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisar"));

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/magnifying47.png"))); // NOI18N
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo de Pessoa"));

        btnGroupTipoPessoa.add(jRPesJuridica);
        jRPesJuridica.setText("Jurídica");
        jRPesJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRPesJuridicaActionPerformed(evt);
            }
        });

        btnGroupTipoPessoa.add(jRPesFisica);
        jRPesFisica.setText("Física");
        jRPesFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRPesFisicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRPesFisica)
                    .addComponent(jRPesJuridica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRPesFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRPesJuridica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));

        jLabel2.setText("Nome :");

        jLabel3.setText("CPF :");

        jLabel15.setText("CNPJ :");

        jTCnpj.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jTCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTCpf.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTNome.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setText("RG :");

        jLabel5.setText("Data de Nascimento :");

        jTDtNasc.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jTDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTDtNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("Naturalidade:");

        jLabel6.setText("Inscrição Estadual :");

        jTIE.setBackground(new java.awt.Color(204, 255, 255));

        jLabel10.setText("Fantasia :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTRg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jTDtNasc)
                            .addComponent(jTIE)))
                    .addComponent(jTNomeFantasia))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(jTCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sexo"));

        BtnGroupSexo.add(jRFem);
        jRFem.setText("Feminino");

        BtnGroupSexo.add(jRMasc);
        jRMasc.setText("Masculino");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRMasc)
                    .addComponent(jRFem))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRFem)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Localização"));

        jLabel16.setText("Endereço :");

        jLabel18.setText("Estado :");

        jLabel17.setText("Cidade :");

        jLabel20.setText("Bairro :");

        jLabel19.setText("Numero :");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel21.setText("CEP :");

        try {
            jTCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("Complemento :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTComplemento))
                            .addComponent(jTBairro)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCep))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contato"));

        jTContato.setBackground(new java.awt.Color(204, 255, 255));
        try {
            jTContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTContato2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Contato 1 :");

        jLabel8.setText("Contato 2 :");

        jLabel12.setText("E-mail :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTContato, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTContato2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTContato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Código"));

        jTCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações Complementares"));

        jLabel9.setText("Observação :");

        jTObs.setColumns(20);
        jTObs.setRows(5);
        jScrollPane1.setViewportView(jTObs);

        jLabel14.setText("Data da última alteração :");

        jTDataAlter.setEditable(false);
        try {
            jTDataAlter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTDataAlter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDataAlter.setEnabled(false);

        jLabel13.setText("Usuário :");

        jTUsuarioCadastro.setEditable(false);
        jTUsuarioCadastro.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDataAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTDataAlter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Situação"));

        jCheckSituacao.setSelected(true);
        jCheckSituacao.setText("Ativo");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckSituacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckSituacao)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/back57.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/save31.png"))); // NOI18N
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/door13.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnSalvar, jButton3, jButton4});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jBtnSalvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void limpatudo() {
        jTCodigo.setText(null);
        jTNome.setText(null);
        jTNaturalidade.setText(null);
        jTNomeFantasia.setText(null);
        jTCpf.setText(null);
        jTCnpj.setText(null);
        jTRg.setText(null);
        jTDtNasc.setText(null);
        jTIE.setText(null);
        jTEndereco.setText(null);
        jTNumero.setText(null);
        jTComplemento.setText(null);
        jTBairro.setText(null);
        jTCidade.setText(null);
        jTCep.setText(null);
        jTContato.setText(null);
        jTContato2.setText(null);
        jTEmail.setText(null);
        jTObs.setText(null);
        jTDataAlter.setText(null);
        jTUsuarioCadastro.setText(null);
    }
    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        //Testa código para saber se esta atualizando ou inserindo novo!
        Controlador c = new Controlador();

        //Testa  tipo de pessoa a ser inserida.
        if (jRPesFisica.isSelected()) {
            String sexo;
            String ativo = "1";

            if ("".equals(jTNome.getText())
                    || "".equals(jTCpf.getText().replaceAll("[.]", "").replaceAll("[-]", "").replaceAll(" ", ""))
                    || "".equals(jTDtNasc.getText().replaceAll("[/]", "").replaceAll(" ", ""))
                    || "".equals(jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""))) {
                JOptionPane.showMessageDialog(this, "Campos obrigatórios vazios,\n favor verifique se há campos obrigatórios vazios", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Validacoes.isValidCPF(jTCpf.getText().replaceAll("[.]", "").replaceAll("[-]", "").replaceAll(" ", ""))) {
                JOptionPane.showMessageDialog(this, "CPF inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
                jTCpf.requestFocus();
                return;
            }
            if (!ValidaData.validaData(jTDtNasc.getText())) {
                JOptionPane.showMessageDialog(this, "Data de nascimento inválida!", "ERRO", JOptionPane.ERROR_MESSAGE);
                jTDtNasc.requestFocus();
                return;
            }

            if (!jRFem.isSelected() && !jRMasc.isSelected()) {
                JOptionPane.showMessageDialog(this, "Selecione o sexo do cadastrante", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (jRFem.isSelected()) {
                sexo = "F";
            } else {
                sexo = "M";
            }

            if (!jCheckSituacao.isSelected()) {
                ativo = "0";
            }
            LocalDate date = new LocalDate();
            if (jTCodigo.getText().equals("")) {
                try {
                    c.inserirCliente(jTNome.getText(), jTCpf.getText().replaceAll("[.]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTRg.getText(), FormataData.dateForBank(jTDtNasc.getText()), sexo, jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTContato2.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTObs.getText(), date.toString(), ativo, jTNaturalidade.getText(), jTEmail.getText(),
                            TelaPrincipal.getIdUsr(), date.toString(), "", "F", jTEndereco.getText(), jTNumero.getText(), jTComplemento.getText(), jTCidade.getText(),
                            jComboEstado.getSelectedItem().toString(), jTBairro.getText(), "", "", jTCep.getText().replaceAll("[-]", "").replaceAll(" ", ""));
                    JOptionPane.showMessageDialog(this, "Inserido com sucesso!");
                    this.limpatudo();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Falha ao inserir dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (!jCheckSituacao.isSelected()) {
                    ativo = "0";
                }
                try {
                    c.atualizaCliente(jTNome.getText(), jTCpf.getText().replaceAll("[.]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTRg.getText(), FormataData.dateForBank(jTDtNasc.getText()), sexo, jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTContato2.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTObs.getText(), ativo, jTNaturalidade.getText(), jTEmail.getText(),
                            TelaPrincipal.getIdUsr(), date.toString(), "", "F", jTEndereco.getText(), jTNumero.getText(), jTComplemento.getText(), jTCidade.getText(),
                            jComboEstado.getSelectedItem().toString(), jTBairro.getText(), "", "", jTCep.getText().replaceAll("[-]", "").replaceAll(" ", ""), jTCodigo.getText());
                    JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
                    this.limpatudo();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Falha ao alterar dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }

            }
            //if(!Validacoes.isValidCPF(jTCpf.getText().replaceAll("[.]","").replaceAll("[-]",""))){
            //  JOptionPane.showMessageDialog(this, "CPF Inválido!","ERRO",JOptionPane.ERROR_MESSAGE);
            //   return;
            //}
        } else if (jRPesJuridica.isSelected()) {
            String sexo = null;
            String ativo = "1";
            if ("".equals(jTNome.getText().replaceAll(" ", ""))
                    || "".equals(jTCnpj.getText().replaceAll("[.]", "").replaceAll("[/]", "").replaceAll("[-]", "").replaceAll(" ", ""))
                    || "".equals(jTIE.getText().replaceAll(" ", ""))
                    || "".equals(jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", "").replaceAll(" ", ""))) {
                JOptionPane.showMessageDialog(this, "Campos obrigatórios vazios,\n favor verifique se há campos obrigatórios vazios", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Validacoes.isValidCNPJ(jTCnpj.getText().replaceAll("[.]", "").replaceAll("[/]", "").replaceAll("[-]", "").replaceAll(" ", ""))) {
                JOptionPane.showMessageDialog(this, "CNPJ inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
                jTCnpj.requestFocus();
                return;
            }
            if (!jCheckSituacao.isSelected()) {
                ativo = "0";
            }
            LocalDate date = new LocalDate();
            if ("".equals(jTCodigo.getText())) {
                try {
                    c.inserirCliente(jTNome.getText(),
                            null, null, null, sexo,
                            jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTContato2.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTObs.getText(), date.toString(), ativo, jTNaturalidade.getText(), jTEmail.getText(),
                            TelaPrincipal.getIdUsr(), date.toString(), jTCnpj.getText().replaceAll("[.]", "").replaceAll("[/]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            "J", jTEndereco.getText(), jTNumero.getText(), jTComplemento.getText(), jTCidade.getText(),
                            jComboEstado.getSelectedItem().toString(), jTBairro.getText(), jTNomeFantasia.getText(), jTIE.getText(), jTCep.getText().replaceAll("[-]", "").replaceAll(" ", ""));
                    JOptionPane.showMessageDialog(this, "Inserido com sucesso!");
                    this.limpatudo();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Falha ao inserir dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {

                try {
                    c.atualizaCliente(jTNome.getText(),
                            null, null, null, sexo,
                            jTContato.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTContato2.getText().replaceAll("[\\(]", "").replaceAll("[\\)]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            jTObs.getText(), ativo, jTNaturalidade.getText(), jTEmail.getText(),
                            TelaPrincipal.getIdUsr(), date.toString(), jTCnpj.getText().replaceAll("[.]", "").replaceAll("[/]", "").replaceAll("[-]", "").replaceAll(" ", ""),
                            "J", jTEndereco.getText(), jTNumero.getText(), jTComplemento.getText(), jTCidade.getText(),
                            jComboEstado.getSelectedItem().toString(), jTBairro.getText(), jTNomeFantasia.getText(), jTIE.getText(),
                            jTCep.getText().replaceAll("[-]", "").replaceAll(" ", ""), jTCodigo.getText());
                    JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
                    this.limpatudo();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Falha ao atualizar dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Para prosseguir, favor selecione um tipo de cadastro!", "ERRO", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jRPesFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPesFisicaActionPerformed
        if (jRPesFisica.isSelected()) {
            jTCnpj.setEnabled(false);
            jTNomeFantasia.setEnabled(false);
            jTIE.setEnabled(false);
            jTCnpj.setText(null);
            jTNomeFantasia.setText(null);
            jTIE.setText(null);
            jTCpf.setEnabled(true);
            jTDtNasc.setEnabled(true);
            jTNaturalidade.setEnabled(true);
            jTRg.setEnabled(true);
            jRFem.setEnabled(true);
            jRMasc.setEnabled(true);
        }
    }//GEN-LAST:event_jRPesFisicaActionPerformed

    private void jRPesJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRPesJuridicaActionPerformed
        if (jRPesJuridica.isSelected()) {
            jTCpf.setEnabled(false);
            jTDtNasc.setEnabled(false);
            jTNaturalidade.setEnabled(false);
            jTRg.setEnabled(false);
            jRFem.setEnabled(false);
            jRMasc.setEnabled(false);

            jTCpf.setText(null);
            jTDtNasc.setText(null);
            jTNaturalidade.setText(null);
            jTRg.setText(null);
            jRFem.setText(null);
            jRMasc.setText(null);

            jTCnpj.setEnabled(true);
            jTNomeFantasia.setEnabled(true);
            jTIE.setEnabled(true);
        }
    }//GEN-LAST:event_jRPesJuridicaActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if (jTPesquisa.getText().equals("")) {
            new BuscaCliente(null, true, jTPesquisa.getText(), this).setVisible(true);
        } else {
            Controlador c = new Controlador();
            ResultSet rs = c.pesquisaClienteNome("%" + jTPesquisa.getText() + "%");
            try {
                if (rs.last() && rs.getRow() == 1) {
                    rs.first();
                    ClienteModel cli = new ClienteModel();
                    cli.setNome(rs.getString("Nome"));
                    cli.setNomeFantasia(rs.getString("NomeFantasia"));
                    cli.setId(rs.getString("id"));
                    cli.setCpf(rs.getString("cpf"));
                    cli.setCnpj(rs.getString("cnpj"));
                    cli.setRg(rs.getString("rg"));
                    cli.setDataNasc(rs.getString("Data_Nasc"));
                    cli.setNaturalidade(rs.getString("Naturalidade"));
                    cli.setIe(rs.getString("ie"));
                    cli.setEndereco(rs.getString("Endereco"));
                    cli.setNumero(rs.getString("Numero"));
                    cli.setComplemento(rs.getString("Complemento"));
                    cli.setBairro(rs.getString("Bairro"));
                    cli.setCidade(rs.getString("Cidade"));
                    cli.setCep(rs.getString("cep"));
                    cli.setEstado(rs.getString("Estado"));
                    cli.setContato(rs.getString("Contato"));
                    cli.setContato2(rs.getString("Contato2"));
                    cli.setEmail(rs.getString("Email"));
                    cli.setObservacao(rs.getString("Observacao"));
                    cli.setDataAlteracao(rs.getString("Data_Alteracao"));
                    cli.setUsuario(rs.getString("login"));
                    cli.setTipoCliente(rs.getString("Tipo_Cliente"));
                    cli.setSexo(rs.getString("Sexo"));
                    if (rs.getInt("Ativo") == 0) {
                        cli.setAtivo(false);
                    } else {
                        cli.setAtivo(true);
                    }
                    
                    this.dispose();
                    
                    new TelaCliente(pai, true, cli).setVisible(true);

                } else {
                    new BuscaCliente(null, true, jTPesquisa.getText(), this).setVisible(true);
                }
                //rs.getRow();
                //rs.first();
                //System.out.println(rs.getString("Nome"));

            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.limpatudo();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCliente dialog = new TelaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupSexo;
    private javax.swing.ButtonGroup btnGroupTipoPessoa;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckSituacao;
    private javax.swing.JComboBox jComboEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRFem;
    private javax.swing.JRadioButton jRMasc;
    private javax.swing.JRadioButton jRPesFisica;
    private javax.swing.JRadioButton jRPesJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JFormattedTextField jTCep;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JFormattedTextField jTCnpj;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JFormattedTextField jTContato;
    private javax.swing.JFormattedTextField jTContato2;
    private javax.swing.JFormattedTextField jTCpf;
    private javax.swing.JFormattedTextField jTDataAlter;
    private javax.swing.JFormattedTextField jTDtNasc;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTIE;
    private javax.swing.JTextField jTNaturalidade;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNomeFantasia;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextArea jTObs;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTextField jTRg;
    private javax.swing.JTextField jTUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
